### ISSUE TITLE
🔍 Search button isn't working

### ISSUE THREAD

**Issue by 1stdevfriend** [jhabarsingh/DSALGO-VISUALIZER#1]
**Path**
./DSALGO-Visualizer/templates/array/array_adt.html

**Image**
![image](https://user-images.githubusercontent.com/27912312/101287703-ead28300-3817-11eb-9e7c-369525b45c27.png)

**Comment by jhabarsingh** [comment]
The Link was incorrect thanks for contributing to this project. 
Now it is working fine I have fixed it.

**Comment by jhabarsingh** [comment]
I have fixed the issue.
Thanks for the contributions.
