### ISSUE TITLE
Bug in BFS traversal animation in queue/bfs.html

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/DSALGO-VISUALIZER#2]
The animation is working fine while traversing except the last traversal.
[CODE](https://github.com/jhabarsingh/DSALGO-Visualizer/blob/main/templates/queue/bfs.html)
[Animation](https://jhabarsingh.github.io/DSALGO-Visualizer/templates/queue/bfs.html)

**Comment by 1stdevfriend** [comment]
I haven't seen any issue in this. Can you please recheck? 
If solved, please close this.

**Comment by jhabarsingh** [comment]
No there is an issue when you will see the animation once again and notice the final traversal.
It's not highlighting the last edge being traversed.

**Comment by 1stdevfriend** [comment]
Hi Jhabar, 
That's because you're using BFS and once all the nodes are being reached. You don't need to do remaining traversals. 

Hope that helped.

**Comment by jhabarsingh** [comment]
Yeah bro I think you are right, again thanks for the contribution.
I am closing the issue.
