### ISSUE TITLE
BUG in Heap Sort.

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/DSALGO-VISUALIZER#3]
CODE: https://github.com/jhabarsingh/DSALGO-VISUALIZER/blob/main/templates/heap/heap_sort.html
ANIMATION: https://jhabarsingh.github.io/DSALGO-VISUALIZER/templates/heap/heap_sort.html

There is something wrong in the heap sort algorithm being implemented.

**Comment by 1stdevfriend** [comment]
Can you please elaborate on the bug?

**Comment by jhabarsingh** [comment]
while we are removing the elements from the heap the array we are getting is not sorted there is a bug in the algorithm.

**Comment by jhabarsingh** [comment]
![Selectionshot_2021-02-15_10:42:03](https://user-images.githubusercontent.com/43932986/107907734-7b48e480-6f7a-11eb-970c-c9f3369c02ed.png)

**Comment by jhabarsingh** [comment]
The Black array is the output array and it is not sorted. 
There is a bug in the algorithm.

**Comment by jhabarsingh** [comment]
```delete_animation()``` function has the bug. 
> **Line No 342**

**Comment by jhabarsingh** [comment]
https://github.com/jhabarsingh/DSALGO-VISUALIZER/commit/78d0f321bc5259e980ef49a7463e9b094f9bc56c

Resolved the issue in the above commit
