### ISSUE TITLE
Adding links to the animation in README.md

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/DSALGO-VISUALIZER#5]
### Example
1. [N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)

### Code
```
[N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)
```
in README.md, we can add a hyperlink to a text using the above syntax

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by jhabarsingh** [comment]
yeah Sure @aditya28sarin.

**Comment by jhabarsingh** [comment]
Again @aditya28sarin, Thanks for the contribution, I am creating a new Issue and closing this one.
