### ISSUE TITLE
Adding Links  in the README.md

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/DSALGO-VISUALIZER#8]
### Example
1. [N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)

### Code
```
[N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)
```
in README.md, we can add a hyperlink to a text using the above syntax

**NOTE** Start From  Linked List Algorithm. #7

**Comment by 96RadhikaJadhav** [comment]
@jhabarsingh  Can I work on the issue?

**Comment by jhabarsingh** [comment]
Yeah sure @96RadhikaJadhav.

**Comment by jhabarsingh** [comment]
I've assigned it to you.

**Comment by 1stdevfriend** [comment]
Fixed at (#12)

**Comment by jhabarsingh** [comment]
Thanks, @SwampDolphin97 and @96RadhikaJadhav for the contribution. I really appreciate that.

**Comment by jhabarsingh** [comment]
@SwampDolphin97, The links you have added are not correct.

**Comment by jhabarsingh** [comment]
Can you please correct them?

**Comment by jhabarsingh** [comment]
Replace `DSALGO-VANILLA` with `DSALGO-VISUALIZER`.

**Comment by jhabarsingh** [comment]
Adds @SwampDolphin97

**Comment by jhabarsingh** [comment]
@SwampDolphin97, I have replaced the `DSALGO-VANILLA` with `DSALGO-VISUALIZER`. So I am closing the issue

**Comment by jhabarsingh** [comment]
Thanks for the contribution
